[user]
name = "Shardul Baral"
email = "shardul@baral.ca"

[ui]
default-command = "log"
graph.style = 'square'

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
fetch = ["git", "fetch"]

[revsets]
log = 'present(@) | ancestors(immutable_heads().., 2) | present(trunk())'

[template-aliases]
'format_timestamp(timestamp)' = 'timestamp.ago()'
