[user]
name = "Shardul Baral"
email = "shardul@baral.ca"

[ui]
default-command = "log"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
fetch = ["git", "fetch"]

[revsets]
log = 'present(@) | ancestors(immutable_heads().., 3) | present(trunk())'
